[project]
name = "telejuke"
version = "0.1.0"
description = "Telephone World Jukebox"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "lgpio>=0.2.2.0",
    "numpy<2.0",
    "pydub>=0.25.1",
    "pyradios>=2.1.1",
    "requests>=2.32.3",
    "sounddevice>=0.5.2",
]
